# extension.toml
# See: https://crates.io/crates/zed_extension_api
id = "playdate"
name = "Playdate"
schema_version = 1
version = "0.1.0"
authors = ["Peter Tripp <petertripp@gmail.com>"]
description = "Playdate support for Zed."
repository = "https://github.com/notpeter/zed-playdate-extension"

[grammars.pdxinfo]
repository = "https://github.com/notpeter/tree-sitter-pdxinfo"
commit = "582981fd8a75ea043055c63935f2a42f535ba72f"

[grammars.animationtxt]
repository = "https://github.com/notpeter/tree-sitter-animationtxt"
commit = "8b4f242519ebaaa6ee2158ccfddf965e11796b02"
