# extension.toml
# See: https://crates.io/crates/zed_extension_api
id = "playdate"
name = "Playdate"
schema_version = 1
version = "0.1.0"
authors = ["Peter Tripp <petertripp@gmail.com>"]
description = "Playdate support for Zed."
repository = "https://github.com/notpeter/zed-playdate-extension"

[grammars.pdxinfo]
repository = "https://github.com/notpeter/tree-sitter-pdxinfo"
commit = "5421120b9ee35db523295731e26aa7a33096e85f"

[grammars.animationtxt]
repository = "https://github.com/notpeter/tree-sitter-animationtxt"
commit = "809d11a74d4eedb606e64cc3f29e306e58df3530"
